CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE organizations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL UNIQUE, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE users (id uuid PRIMARY KEY, email text NOT NULL, display_name text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE memberships (organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, role text NOT NULL CHECK (role IN ('owner', 'admin', 'supervisor', 'agent')), PRIMARY KEY (organization_id, user_id));
CREATE TABLE app_sessions (token_hash text PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX app_sessions_expiry_idx ON app_sessions (expires_at);
CREATE TABLE whatsapp_accounts (phone_number_id text PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE contacts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, phone_number text NOT NULL, name text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (organization_id, phone_number));
CREATE TABLE conversations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, contact_id uuid NOT NULL REFERENCES contacts(id) ON DELETE CASCADE, status text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (organization_id, contact_id));
CREATE TABLE messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, conversation_id uuid NOT NULL REFERENCES conversations(id) ON DELETE CASCADE, direction text NOT NULL CHECK (direction IN ('inbound', 'outbound')), type text NOT NULL, body text, status text NOT NULL DEFAULT 'received' CHECK (status IN ('pending', 'sent', 'delivered', 'read', 'failed', 'received')), provider_message_id text UNIQUE, error_code text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX messages_conversation_idx ON messages (conversation_id, created_at);
CREATE TABLE webhook_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), event_hash text NOT NULL UNIQUE, payload jsonb NOT NULL, received_at timestamptz NOT NULL DEFAULT now());
