const router = require('express').Router();
const controller = require('../controllers/conversation.controller');
const { requireUser } = require('../middleware/auth.middleware');
const audioMimeTypes = new Set(['audio/aac', 'audio/mp4', 'audio/mpeg', 'audio/amr', 'audio/ogg', 'audio/opus', 'audio/webm']);
const isAudio = (req) => audioMimeTypes.has((req.get('content-type') || '').split(';')[0]);
const imageMimeTypes = new Set(['image/jpeg', 'image/png', 'image/webp']);
const videoMimeTypes = new Set(['video/mp4', 'video/3gpp', 'video/quicktime']);
const isPdf = (req) => (req.get('content-type') || '').split(';')[0] === 'application/pdf';
const isImage = (req) => imageMimeTypes.has((req.get('content-type') || '').split(';')[0]);
const isVideo = (req) => videoMimeTypes.has((req.get('content-type') || '').split(';')[0]);
router.use(requireUser);
router.get('/', controller.list);
router.post('/', controller.create);
router.get('/:id/messages', controller.messages);
router.get('/:id/document-options', controller.documentOptions);
router.get('/:id/messages/:messageId/media', controller.media);
router.post('/:id/messages/text', controller.sendText);
router.post('/:id/messages/document', controller.sendDocument);
router.post('/:id/messages/document/upload', require('express').raw({ type: isPdf, limit: '25mb' }), controller.uploadDocument);
router.post('/:id/messages/audio', require('express').raw({ type: isAudio, limit: '16mb' }), controller.sendAudio);
router.post('/:id/messages/image', require('express').raw({ type: isImage, limit: '5mb' }), controller.sendImage);
router.post('/:id/messages/video', require('express').raw({ type: isVideo, limit: '16mb' }), controller.sendVideo);
module.exports = router;
