const router = require('express').Router();
const controller = require('../controllers/settings.controller');
const { requireUser, requireRole } = require('../middleware/auth.middleware');
const isPdf = (req) => (req.get('content-type') || '').split(';')[0] === 'application/pdf';
const isImage = (req) => ['image/jpeg', 'image/png', 'image/webp'].includes((req.get('content-type') || '').split(';')[0].toLowerCase());
router.post('/whatsapp-account', requireUser, requireRole('owner', 'admin'), controller.connectWhatsApp);
router.post('/catalog-document', requireUser, requireRole('owner', 'admin'), controller.configureCatalogDocument);
router.get('/document-templates', requireUser, controller.listDocumentTemplates);
router.post('/document-templates/upload', requireUser, requireRole('owner', 'admin'), require('express').raw({ type: isPdf, limit: '25mb' }), controller.uploadDocumentTemplate);
router.patch('/document-templates/:id', requireUser, requireRole('owner', 'admin'), controller.updateDocumentTemplate);
router.delete('/document-templates/:id', requireUser, requireRole('owner', 'admin'), controller.deleteDocumentTemplate);
router.get('/entrepreneur-packages', requireUser, controller.listEntrepreneurPackages);
router.get('/entrepreneur-packages/:id/media', requireUser, controller.entrepreneurPackageMedia);
router.post('/entrepreneur-packages/upload', requireUser, requireRole('owner', 'admin'), require('express').raw({ type: isImage, limit: '5mb' }), controller.uploadEntrepreneurPackage);
router.patch('/entrepreneur-packages/:id', requireUser, requireRole('owner', 'admin'), controller.updateEntrepreneurPackage);
router.delete('/entrepreneur-packages/:id', requireUser, requireRole('owner', 'admin'), controller.deleteEntrepreneurPackage);
module.exports = router;
