const router = require('express').Router();
const controller = require('../controllers/shipping.controller');
const { requireUser, requireRole } = require('../middleware/auth.middleware');
router.use(requireUser);
router.get('/settings', controller.settings);
router.put('/settings', requireRole('owner', 'admin'), controller.saveSettings);
router.get('/saved', controller.listSaved);
router.get('/customers', controller.customers);
router.post('/saved/addresses', controller.saveAddress);
router.post('/saved/packages', controller.savePackage);
router.delete('/saved/:kind/:id', controller.deleteSaved);
router.get('/shipments', controller.list);
router.post('/quote', controller.quote);
router.post('/generate', requireRole('owner', 'admin'), controller.generate);
module.exports = router;
